begin;

create extension if not exists pgcrypto;

-- ============================================================================
-- Safari Custom WhatsApp OTP
-- Meta WhatsApp Cloud API handles OTP delivery.
-- Supabase built-in Phone provider / Twilio is NOT required.
-- ============================================================================

create table if not exists public.auth_otp_challenges (
  id uuid primary key default gen_random_uuid(),

  phone text not null,

  purpose text not null
    check (purpose in ('signup', 'forgot_password')),

  otp_hash text not null,

  attempts integer not null default 0,
  max_attempts integer not null default 5,

  expires_at timestamptz not null,
  verified_at timestamptz,
  consumed_at timestamptz,

  reset_token_hash text,

  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now()
);

create index if not exists auth_otp_challenges_lookup_idx
  on public.auth_otp_challenges(phone, purpose, created_at desc);

create index if not exists auth_otp_challenges_expiry_idx
  on public.auth_otp_challenges(expires_at)
  where consumed_at is null;

create table if not exists public.whatsapp_webhook_events (
  id bigint generated by default as identity primary key,

  event_type text,
  phone_number_id text,
  whatsapp_business_account_id text,
  message_id text,
  status text,
  recipient_id text,

  payload jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now()
);

create index if not exists whatsapp_webhook_events_message_idx
  on public.whatsapp_webhook_events(message_id, created_at desc);

-- OTP/webhook tables are backend-only.
alter table public.auth_otp_challenges enable row level security;
alter table public.whatsapp_webhook_events enable row level security;

revoke all on public.auth_otp_challenges from anon, authenticated;
revoke all on public.whatsapp_webhook_events from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Mobile users now use an internal synthetic Supabase email identity.
-- The real phone/email remain in profiles / metadata.
-- This means Supabase Phone Provider can remain OFF.
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  metadata jsonb;
  resolved_account_type text;
  metadata_phone text;
  metadata_email text;
  is_mobile_phone_auth boolean;
begin
  metadata := coalesce(new.raw_user_meta_data, '{}'::jsonb);

  resolved_account_type :=
    coalesce(
      nullif(metadata ->> 'account_type', ''),
      'passenger'
    );

  metadata_phone := nullif(metadata ->> 'phone', '');
  metadata_email := nullif(metadata ->> 'email', '');

  is_mobile_phone_auth :=
    coalesce((metadata ->> 'is_mobile_phone_auth')::boolean, false);

  insert into public.profiles (
    id,
    full_name,
    email,
    phone,
    account_type,
    app_mode,
    admin_role,
    merchant_type,
    status,
    country_code,
    is_onboarded
  )
  values (
    new.id,
    nullif(metadata ->> 'full_name', ''),

    case
      when is_mobile_phone_auth then metadata_email
      else coalesce(metadata_email, new.email)
    end,

    coalesce(metadata_phone, new.phone),

    resolved_account_type,

    case
      when resolved_account_type in ('passenger', 'driver')
      then coalesce(
        nullif(metadata ->> 'app_mode', ''),
        resolved_account_type
      )
      else null
    end,

    nullif(metadata ->> 'admin_role', ''),
    nullif(metadata ->> 'merchant_type', ''),

    case
      when is_mobile_phone_auth then 'pending'
      when resolved_account_type = 'merchant' then 'pending'
      else 'active'
    end,

    coalesce(nullif(metadata ->> 'country_code', ''), 'PK'),
    false
  )
  on conflict (id) do update
  set
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    email = coalesce(excluded.email, public.profiles.email),
    phone = coalesce(excluded.phone, public.profiles.phone),
    account_type = excluded.account_type,
    app_mode = coalesce(excluded.app_mode, public.profiles.app_mode),
    admin_role = coalesce(excluded.admin_role, public.profiles.admin_role),
    merchant_type = coalesce(excluded.merchant_type, public.profiles.merchant_type),
    country_code = excluded.country_code,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert or update of raw_user_meta_data, email, phone
on auth.users
for each row execute procedure public.handle_new_auth_user();

commit;
