begin;

create extension if not exists pgcrypto;

create table if not exists public.system_health (
  id bigint generated by default as identity primary key,
  name text not null default 'safari',
  created_at timestamptz not null default now()
);

insert into public.system_health (name)
select 'safari'
where not exists (select 1 from public.system_health);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,

  full_name text,
  email text,
  phone text,
  avatar_url text,

  account_type text not null default 'passenger'
    check (
      account_type in (
        'passenger',
        'driver',
        'delivery_partner',
        'administration',
        'merchant'
      )
    ),

  app_mode text
    check (
      app_mode is null
      or app_mode in ('passenger', 'driver')
    ),

  admin_role text
    check (
      admin_role is null
      or admin_role in (
        'super_admin',
        'admin',
        'operations_manager',
        'finance_manager',
        'support'
      )
    ),

  merchant_type text
    check (
      merchant_type is null
      or merchant_type in (
        'food',
        'grocery',
        'pharmacy',
        'services'
      )
    ),

  status text not null default 'active'
    check (
      status in (
        'pending',
        'active',
        'suspended',
        'blocked'
      )
    ),

  country_code text not null default 'PK'
    check (country_code in ('PK', 'DE')),

  is_onboarded boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_unique
  on public.profiles(lower(email))
  where email is not null;

create unique index if not exists profiles_phone_unique
  on public.profiles(phone)
  where phone is not null;

create index if not exists profiles_account_type_idx
  on public.profiles(account_type);

create index if not exists profiles_status_idx
  on public.profiles(status);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  metadata jsonb;
  resolved_account_type text;
begin
  metadata := coalesce(new.raw_user_meta_data, '{}'::jsonb);

  resolved_account_type :=
    coalesce(
      nullif(metadata ->> 'account_type', ''),
      'passenger'
    );

  insert into public.profiles (
    id,
    full_name,
    email,
    phone,
    account_type,
    app_mode,
    admin_role,
    merchant_type,
    status,
    country_code,
    is_onboarded
  )
  values (
    new.id,
    nullif(metadata ->> 'full_name', ''),
    coalesce(new.email, nullif(metadata ->> 'email', '')),
    new.phone,
    resolved_account_type,
    case
      when resolved_account_type in ('passenger', 'driver')
      then coalesce(nullif(metadata ->> 'app_mode', ''), resolved_account_type)
      else null
    end,
    nullif(metadata ->> 'admin_role', ''),
    nullif(metadata ->> 'merchant_type', ''),
    case
      when resolved_account_type = 'merchant' then 'pending'
      else 'active'
    end,
    coalesce(nullif(metadata ->> 'country_code', ''), 'PK'),
    false
  )
  on conflict (id) do update
  set
    full_name = excluded.full_name,
    email = excluded.email,
    phone = excluded.phone,
    account_type = excluded.account_type,
    app_mode = excluded.app_mode,
    admin_role = coalesce(excluded.admin_role, public.profiles.admin_role),
    merchant_type = coalesce(excluded.merchant_type, public.profiles.merchant_type),
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert or update of raw_user_meta_data, email, phone
on auth.users
for each row execute procedure public.handle_new_auth_user();

alter table public.system_health enable row level security;
alter table public.profiles enable row level security;

drop policy if exists "authenticated can read own profile"
  on public.profiles;

create policy "authenticated can read own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

-- Direct client profile writes are intentionally not granted.
-- Mobile/Admin business writes go through the Safari backend service-role client.

grant select on public.profiles to authenticated;

commit;
