begin;

-- ============================================================================
-- Safari Phase 08
-- Active Ride Lifecycle + Location Tracking
-- ============================================================================

create table if not exists public.driver_locations (
  driver_id uuid primary key references public.profiles(id) on delete cascade,

  ride_id uuid references public.rides(id) on delete set null,

  latitude double precision not null,
  longitude double precision not null,

  heading numeric(8,2),
  speed_kph numeric(8,2),
  accuracy_meters numeric(10,2),

  is_online boolean not null default true,

  recorded_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists driver_locations_ride_idx
  on public.driver_locations(ride_id);

create index if not exists driver_locations_online_idx
  on public.driver_locations(is_online, updated_at desc);

create table if not exists public.ride_tracking_points (
  id bigint generated by default as identity primary key,

  ride_id uuid not null references public.rides(id) on delete cascade,
  driver_id uuid not null references public.profiles(id) on delete cascade,

  latitude double precision not null,
  longitude double precision not null,

  heading numeric(8,2),
  speed_kph numeric(8,2),
  accuracy_meters numeric(10,2),

  recorded_at timestamptz not null default now()
);

create index if not exists ride_tracking_points_ride_idx
  on public.ride_tracking_points(ride_id, recorded_at desc);

alter table public.rides
  add column if not exists driver_arrival_eta_minutes integer,
  add column if not exists driver_distance_to_pickup_km numeric(10,2),
  add column if not exists start_otp text,
  add column if not exists actual_pickup_latitude double precision,
  add column if not exists actual_pickup_longitude double precision,
  add column if not exists actual_dropoff_latitude double precision,
  add column if not exists actual_dropoff_longitude double precision,
  add column if not exists last_driver_location_at timestamptz;

alter table public.driver_locations enable row level security;
alter table public.ride_tracking_points enable row level security;

drop policy if exists "drivers can read own location"
  on public.driver_locations;

create policy "drivers can read own location"
on public.driver_locations
for select
to authenticated
using (auth.uid() = driver_id);

drop policy if exists "passengers can read assigned driver location"
  on public.driver_locations;

create policy "passengers can read assigned driver location"
on public.driver_locations
for select
to authenticated
using (
  exists (
    select 1
    from public.rides r
    where r.id = driver_locations.ride_id
      and r.passenger_id = auth.uid()
      and r.driver_id = driver_locations.driver_id
  )
);

drop policy if exists "ride participants can read ride tracking"
  on public.ride_tracking_points;

create policy "ride participants can read ride tracking"
on public.ride_tracking_points
for select
to authenticated
using (
  exists (
    select 1
    from public.rides r
    where r.id = ride_tracking_points.ride_id
      and (
        r.passenger_id = auth.uid()
        or r.driver_id = auth.uid()
      )
  )
);

grant select on public.driver_locations to authenticated;
grant select on public.ride_tracking_points to authenticated;

commit;
