begin;

-- ============================================================================
-- Safari Phase 15
-- Notifications + Realtime-ready events
-- ============================================================================

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null references public.profiles(id) on delete cascade,

  notification_type text not null
    check (
      notification_type in (
        'ride',
        'food',
        'grocery',
        'pharmacy',
        'services',
        'payment',
        'wallet',
        'account',
        'promotion',
        'system'
      )
    ),

  title text not null,
  body text not null,

  data jsonb not null default '{}'::jsonb,

  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high')),

  is_read boolean not null default false,
  read_at timestamptz,

  created_at timestamptz not null default now()
);

create index if not exists notifications_user_idx
  on public.notifications(user_id, is_read, created_at desc);

create table if not exists public.device_tokens (
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null references public.profiles(id) on delete cascade,

  platform text not null
    check (platform in ('android', 'ios', 'web')),

  push_provider text not null default 'expo'
    check (push_provider in ('expo', 'fcm', 'apns', 'web')),

  token text not null,

  device_name text,
  app_version text,

  is_active boolean not null default true,
  last_seen_at timestamptz not null default now(),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (push_provider, token)
);

create index if not exists device_tokens_user_idx
  on public.device_tokens(user_id, is_active);

create table if not exists public.realtime_events (
  id bigint generated by default as identity primary key,

  channel text not null,
  event_type text not null,

  user_id uuid references public.profiles(id) on delete cascade,
  entity_type text,
  entity_id uuid,

  payload jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now()
);

create index if not exists realtime_events_channel_idx
  on public.realtime_events(channel, created_at desc);

create index if not exists realtime_events_user_idx
  on public.realtime_events(user_id, created_at desc);

alter table public.notifications enable row level security;
alter table public.device_tokens enable row level security;
alter table public.realtime_events enable row level security;

drop policy if exists "users can read own notifications"
  on public.notifications;

create policy "users can read own notifications"
on public.notifications
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can read own device tokens"
  on public.device_tokens;

create policy "users can read own device tokens"
on public.device_tokens
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can read own realtime events"
  on public.realtime_events;

create policy "users can read own realtime events"
on public.realtime_events
for select
to authenticated
using (
  user_id = auth.uid()
  or user_id is null
);

grant select on public.notifications to authenticated;
grant select on public.device_tokens to authenticated;
grant select on public.realtime_events to authenticated;

-- Enable realtime publication safely.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'realtime_events'
  ) then
    alter publication supabase_realtime add table public.realtime_events;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'rides'
  ) then
    alter publication supabase_realtime add table public.rides;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'driver_locations'
  ) then
    alter publication supabase_realtime add table public.driver_locations;
  end if;
end $$;

commit;
